class profile::webserver {
  class { '::apache':
    mpm_module => 'prefork',
  }
  contain ::apache

  contain ::apache::mod::rewrite
  contain ::apache::mod::php

  file { 'php timezone':
    ensure  => file,
    path    => '/etc/php5/apache2/conf.d/timezone.ini',
    content => "; generated by Puppet\ndate.timezone=${::timezone}\n",
    require => Class['::apache::mod::php'],
    notify  => Class['apache::service'],
  }
}
